name: docker build
on: push
permissions:
  id-token: write
  contents: read
jobs:
  ecr-login:
    name: ECR role checking
    runs-on: ubuntu-latest
    steps:
      - name: setup ECR
        uses: actions/checkout@v2
      - name: setup ECR details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::489994096722:role/saad-ecr-role
          aws-region: us-east-1
      - name: login to ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{secrets.ECR_REPO}}
            IMAGE_TAG: latest
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
      
          
          
        
