name: docker build
on: push
permissions:
  id-token: write
  contents: read
jobs:
  ecr-login:
    name: ECR role checking
    runs-on: ubuntu-latest
    steps:
      - name: setup ECR
        uses: actions/checkout@v2
      - name: setup ECR details
        with:
          role-to-assume: arn:aws:iam::489994096722:role/saad-ecr-role
          aws-region: us-east-1
      - name: login to ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
          
      
          
          
        
