name: hello-world
on: push
jobs:
  listS3:
    runs-on: ubuntu-latest
    steps:
      -  run: aws s3 ls
         env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
          
        
