name: hello-world
on: push
permissions:
  id-token: write
  contents: read
jobs:
  listS3:
    runs-on: ubuntu-latest
    steps:
      - name: configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::489994096722:role/saad-s3-rolee
          aws-region: us-east-1
      - name: run command
        run: 
           aws s3 ls
          
      
          
          
        
