name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
      - uses: chrislennon/action-aws-cli@v1.1
      -  run: aws s3 ls
         env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
        
